#!/bin/bash

# This script installs a Python virtual environment

set -euo pipefail

error_exit() {
  # Print error message and exit with status 1
  echo
  echo "  ERROR: $1"
  echo
  exit 1
}


if [ ! -f "venv.conf" ]; then
  error_exit "No venv.conf file found!"
fi

. ./venv.conf

usrname="$(whoami)"

# Set up Python executable path
PYTHON_INSTALL_DIR="/opt/python/${PYTHON_VERSION_TO_INSTALL}"
PYTHON_EXEC="${PYTHON_INSTALL_DIR}/bin/python${PYTHON_VERSION_TO_INSTALL%.*}"


# create venv into the cloned repository folder: /<proj_dir>/env
cd ..
mkdir -p env
cd env
$PYTHON_EXEC -m venv .
VENV_DIR="$(pwd)"

cd ../install
source "$VENV_DIR/bin/activate"
pip install --upgrade pip setuptools wheel
pip install -r requirements.txt

exit 0
